# Site settings
title: Joey
email: zhouyizirui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Computer Science professional student, interested in Distributed Systems and Networking.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zhouyizirui
github_username:  zhouyizirui

# Build settings
markdown: kramdown
